' Gambas module file

Public $Con As New Connection
Public $CurrentUserID As Integer ' this will save the login id of the user to use as separator to view each account's saved passwords.

Public Sub Connect()
  
  $Con.Type = "sqlite3"
  $Con.Host = Application.Path
  $Con.Name = "password"
  
  Try $Con.Open()
  
  If Error Then 
    Message.Error("Connection failed: " & Error.Text)
  Else 
    Print "Database connected successfully!"
  Endif
  
End
